### ISSUE TITLE
ChatGPT models

### ISSUE THREAD

**Issue by alexruben007** [Leniolabs/ai-data-dashboard#12]
Your script is very cool. I just want ton ask if you have plan to add GPT 3.5-turbo and 4, which use different call method.
Best regards

**Comment by apresmoi** [comment]
Hello @alexruben007 ! That's a good idea, we could add support for different models and a dropdown to choose between them in our settings window.

**Comment by apresmoi** [comment]
This has been solved in #13 

Thanks!
